stages:
  - tests
  - report
  - deploy

run_tests:
  stage: tests
  tags:
    - docker
  image: python:3.12.3-alpine3.20
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest --reruns 3 -n 4 --alluredir=allure_results/ -v
  allow_failure: true
  artifacts:
    when: always
    paths:
      - allure_results
    expire_in: 10 days

allure_report:
  stage: report
  tags:
    - docker
  image: frankescobar/allure-docker-service
  script:
    - allure generate -c allure_results -o allure_report
  allow_failure: true
  artifacts:
    when: always
    paths:
      - allure_results
      - allure_report
    expire_in: 10 days
  rules:
    - when: always

pages:
  stage: deploy
  tags:
    - docker
  script:
    - mkdir public
    - mv allure_report/* public
  artifacts:
    paths:
      - public
  rules:
    - when: always
