services:
  api_tests:
    image: tests
    build: .
    volumes:
      - .:/test_project
    command: /bin/sh -c "pytest --reruns 3 -n 4 --alluredir=allure-results/ -v"

  report:
    image: tests
    build: .
    volumes:
      - .:/test_project
    command: /bin/sh -c "allure generate allure-results --clean -o allure-report"
