services:
  api_tests:
    image: tests
    build: .
    volumes:
      - .:/test_project
    command: /bin/sh -c "pytest --reruns 3 -n 4 --alluredir=allure_results/ -v"

  report:
    image: tests
    build: .
    volumes:
      - .:/test_project
    command: /bin/sh -c "allure generate allure_results --clean -o allure_report"
